version: '3.4'

services:
  androsov.api:
    image: ${DOCKER_REGISTRY-}androsovapi
    build:
      context: .
      dockerfile: Androsov.API/Dockerfile

  androsov.web:
    image: ${DOCKER_REGISTRY-}androsovweb
    build:
      context: .
      dockerfile: Androsov.Web\Dockerfile
