version: '3.4'

services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Secret1234

  androsov.api:
    image: ${DOCKER_REGISTRY-}androsovapi
    build:
      context: .
      dockerfile: Androsov.API\Dockerfile
    ports:
        - '5000:80' 
    depends_on:
        - mssql
      
  androsov.web:
    image: ${DOCKER_REGISTRY-}androsovweb
    build:
      context: .
      dockerfile: Androsov.Web\Dockerfile
    ports:
        - '5001:80' 
    depends_on:
        - androsov.api