version: '3.4'

services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Secret1234
    networks:
      - my-network

  androsov.api:
    image: ${DOCKER_REGISTRY-}androsovapi
    container_name: androsovapi
    build:
      context: .
      dockerfile: Androsov.API\Dockerfile
    ports:
        - '9000:80' 
        - '9001:443' 
    depends_on:
        - mssql
    networks:
      - my-network
      
  androsov.web:
    image: ${DOCKER_REGISTRY-}androsovweb
    container_name: androsovweb
    build:
      context: .
      dockerfile: Androsov.Web\Dockerfile
    ports:
        - '9002:80' 
        - '9003:443' 
    depends_on:
        - androsov.api
    networks:
      - my-network


networks:
  my-network:
    driver: bridge